<?php


/**
 * Base class that represents a query for the 'compresion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat Jan  4 18:51:01 2014
 *
 * @method CompresionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method CompresionQuery orderByCompresion($order = Criteria::ASC) Order by the compresion column
 *
 * @method CompresionQuery groupById() Group by the id column
 * @method CompresionQuery groupByCompresion() Group by the compresion column
 *
 * @method CompresionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method CompresionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method CompresionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method CompresionQuery leftJoinDataset($relationAlias = null) Adds a LEFT JOIN clause to the query using the Dataset relation
 * @method CompresionQuery rightJoinDataset($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Dataset relation
 * @method CompresionQuery innerJoinDataset($relationAlias = null) Adds a INNER JOIN clause to the query using the Dataset relation
 *
 * @method Compresion findOne(PropelPDO $con = null) Return the first Compresion matching the query
 * @method Compresion findOneOrCreate(PropelPDO $con = null) Return the first Compresion matching the query, or a new Compresion object populated from the query conditions when no match is found
 *
 * @method Compresion findOneById(int $id) Return the first Compresion filtered by the id column
 * @method Compresion findOneByCompresion(string $compresion) Return the first Compresion filtered by the compresion column
 *
 * @method array findById(int $id) Return Compresion objects filtered by the id column
 * @method array findByCompresion(string $compresion) Return Compresion objects filtered by the compresion column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseCompresionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseCompresionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Compresion', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new CompresionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     CompresionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return CompresionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof CompresionQuery) {
            return $criteria;
        }
        $query = new CompresionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Compresion|Compresion[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = CompresionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(CompresionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Compresion A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `COMPRESION` FROM `compresion` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Compresion();
            $obj->hydrate($row);
            CompresionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Compresion|Compresion[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Compresion[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return CompresionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(CompresionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return CompresionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(CompresionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CompresionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(CompresionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the compresion column
     *
     * Example usage:
     * <code>
     * $query->filterByCompresion('fooValue');   // WHERE compresion = 'fooValue'
     * $query->filterByCompresion('%fooValue%'); // WHERE compresion LIKE '%fooValue%'
     * </code>
     *
     * @param     string $compresion The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CompresionQuery The current query, for fluid interface
     */
    public function filterByCompresion($compresion = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($compresion)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $compresion)) {
                $compresion = str_replace('*', '%', $compresion);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CompresionPeer::COMPRESION, $compresion, $comparison);
    }

    /**
     * Filter the query by a related Dataset object
     *
     * @param   Dataset|PropelObjectCollection $dataset  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   CompresionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByDataset($dataset, $comparison = null)
    {
        if ($dataset instanceof Dataset) {
            return $this
                ->addUsingAlias(CompresionPeer::ID, $dataset->getCompresionId(), $comparison);
        } elseif ($dataset instanceof PropelObjectCollection) {
            return $this
                ->useDatasetQuery()
                ->filterByPrimaryKeys($dataset->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByDataset() only accepts arguments of type Dataset or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Dataset relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return CompresionQuery The current query, for fluid interface
     */
    public function joinDataset($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Dataset');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Dataset');
        }

        return $this;
    }

    /**
     * Use the Dataset relation Dataset object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   DatasetQuery A secondary query class using the current class as primary query
     */
    public function useDatasetQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinDataset($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Dataset', 'DatasetQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Compresion $compresion Object to remove from the list of results
     *
     * @return CompresionQuery The current query, for fluid interface
     */
    public function prune($compresion = null)
    {
        if ($compresion) {
            $this->addUsingAlias(CompresionPeer::ID, $compresion->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
