<?php


/**
 * Base class that represents a query for the 'formato' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat Jan  4 18:51:01 2014
 *
 * @method FormatoQuery orderById($order = Criteria::ASC) Order by the id column
 * @method FormatoQuery orderByFormato($order = Criteria::ASC) Order by the formato column
 *
 * @method FormatoQuery groupById() Group by the id column
 * @method FormatoQuery groupByFormato() Group by the formato column
 *
 * @method FormatoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method FormatoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method FormatoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method FormatoQuery leftJoinDataset($relationAlias = null) Adds a LEFT JOIN clause to the query using the Dataset relation
 * @method FormatoQuery rightJoinDataset($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Dataset relation
 * @method FormatoQuery innerJoinDataset($relationAlias = null) Adds a INNER JOIN clause to the query using the Dataset relation
 *
 * @method Formato findOne(PropelPDO $con = null) Return the first Formato matching the query
 * @method Formato findOneOrCreate(PropelPDO $con = null) Return the first Formato matching the query, or a new Formato object populated from the query conditions when no match is found
 *
 * @method Formato findOneById(int $id) Return the first Formato filtered by the id column
 * @method Formato findOneByFormato(string $formato) Return the first Formato filtered by the formato column
 *
 * @method array findById(int $id) Return Formato objects filtered by the id column
 * @method array findByFormato(string $formato) Return Formato objects filtered by the formato column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseFormatoQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseFormatoQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Formato', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new FormatoQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     FormatoQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return FormatoQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof FormatoQuery) {
            return $criteria;
        }
        $query = new FormatoQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Formato|Formato[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = FormatoPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(FormatoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Formato A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `FORMATO` FROM `formato` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Formato();
            $obj->hydrate($row);
            FormatoPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Formato|Formato[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Formato[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return FormatoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(FormatoPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return FormatoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(FormatoPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return FormatoQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(FormatoPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the formato column
     *
     * Example usage:
     * <code>
     * $query->filterByFormato('fooValue');   // WHERE formato = 'fooValue'
     * $query->filterByFormato('%fooValue%'); // WHERE formato LIKE '%fooValue%'
     * </code>
     *
     * @param     string $formato The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return FormatoQuery The current query, for fluid interface
     */
    public function filterByFormato($formato = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($formato)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $formato)) {
                $formato = str_replace('*', '%', $formato);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(FormatoPeer::FORMATO, $formato, $comparison);
    }

    /**
     * Filter the query by a related Dataset object
     *
     * @param   Dataset|PropelObjectCollection $dataset  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   FormatoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByDataset($dataset, $comparison = null)
    {
        if ($dataset instanceof Dataset) {
            return $this
                ->addUsingAlias(FormatoPeer::ID, $dataset->getFormatoId(), $comparison);
        } elseif ($dataset instanceof PropelObjectCollection) {
            return $this
                ->useDatasetQuery()
                ->filterByPrimaryKeys($dataset->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByDataset() only accepts arguments of type Dataset or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Dataset relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return FormatoQuery The current query, for fluid interface
     */
    public function joinDataset($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Dataset');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Dataset');
        }

        return $this;
    }

    /**
     * Use the Dataset relation Dataset object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   DatasetQuery A secondary query class using the current class as primary query
     */
    public function useDatasetQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinDataset($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Dataset', 'DatasetQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Formato $formato Object to remove from the list of results
     *
     * @return FormatoQuery The current query, for fluid interface
     */
    public function prune($formato = null)
    {
        if ($formato) {
            $this->addUsingAlias(FormatoPeer::ID, $formato->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
