<?php


/**
 * Base class that represents a query for the 'dataset_valoracion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat Jan  4 18:51:01 2014
 *
 * @method DatasetValoracionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method DatasetValoracionQuery orderByDatasetId($order = Criteria::ASC) Order by the dataset_id column
 * @method DatasetValoracionQuery orderByPromedio($order = Criteria::ASC) Order by the promedio column
 * @method DatasetValoracionQuery orderByNvotos($order = Criteria::ASC) Order by the nvotos column
 *
 * @method DatasetValoracionQuery groupById() Group by the id column
 * @method DatasetValoracionQuery groupByDatasetId() Group by the dataset_id column
 * @method DatasetValoracionQuery groupByPromedio() Group by the promedio column
 * @method DatasetValoracionQuery groupByNvotos() Group by the nvotos column
 *
 * @method DatasetValoracionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method DatasetValoracionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method DatasetValoracionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method DatasetValoracionQuery leftJoinDataset($relationAlias = null) Adds a LEFT JOIN clause to the query using the Dataset relation
 * @method DatasetValoracionQuery rightJoinDataset($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Dataset relation
 * @method DatasetValoracionQuery innerJoinDataset($relationAlias = null) Adds a INNER JOIN clause to the query using the Dataset relation
 *
 * @method DatasetValoracion findOne(PropelPDO $con = null) Return the first DatasetValoracion matching the query
 * @method DatasetValoracion findOneOrCreate(PropelPDO $con = null) Return the first DatasetValoracion matching the query, or a new DatasetValoracion object populated from the query conditions when no match is found
 *
 * @method DatasetValoracion findOneById(int $id) Return the first DatasetValoracion filtered by the id column
 * @method DatasetValoracion findOneByDatasetId(int $dataset_id) Return the first DatasetValoracion filtered by the dataset_id column
 * @method DatasetValoracion findOneByPromedio(int $promedio) Return the first DatasetValoracion filtered by the promedio column
 * @method DatasetValoracion findOneByNvotos(int $nvotos) Return the first DatasetValoracion filtered by the nvotos column
 *
 * @method array findById(int $id) Return DatasetValoracion objects filtered by the id column
 * @method array findByDatasetId(int $dataset_id) Return DatasetValoracion objects filtered by the dataset_id column
 * @method array findByPromedio(int $promedio) Return DatasetValoracion objects filtered by the promedio column
 * @method array findByNvotos(int $nvotos) Return DatasetValoracion objects filtered by the nvotos column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseDatasetValoracionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseDatasetValoracionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'DatasetValoracion', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new DatasetValoracionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     DatasetValoracionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return DatasetValoracionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof DatasetValoracionQuery) {
            return $criteria;
        }
        $query = new DatasetValoracionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   DatasetValoracion|DatasetValoracion[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = DatasetValoracionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(DatasetValoracionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   DatasetValoracion A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `DATASET_ID`, `PROMEDIO`, `NVOTOS` FROM `dataset_valoracion` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new DatasetValoracion();
            $obj->hydrate($row);
            DatasetValoracionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return DatasetValoracion|DatasetValoracion[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|DatasetValoracion[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(DatasetValoracionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(DatasetValoracionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(DatasetValoracionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the dataset_id column
     *
     * Example usage:
     * <code>
     * $query->filterByDatasetId(1234); // WHERE dataset_id = 1234
     * $query->filterByDatasetId(array(12, 34)); // WHERE dataset_id IN (12, 34)
     * $query->filterByDatasetId(array('min' => 12)); // WHERE dataset_id > 12
     * </code>
     *
     * @see       filterByDataset()
     *
     * @param     mixed $datasetId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function filterByDatasetId($datasetId = null, $comparison = null)
    {
        if (is_array($datasetId)) {
            $useMinMax = false;
            if (isset($datasetId['min'])) {
                $this->addUsingAlias(DatasetValoracionPeer::DATASET_ID, $datasetId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($datasetId['max'])) {
                $this->addUsingAlias(DatasetValoracionPeer::DATASET_ID, $datasetId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DatasetValoracionPeer::DATASET_ID, $datasetId, $comparison);
    }

    /**
     * Filter the query on the promedio column
     *
     * Example usage:
     * <code>
     * $query->filterByPromedio(1234); // WHERE promedio = 1234
     * $query->filterByPromedio(array(12, 34)); // WHERE promedio IN (12, 34)
     * $query->filterByPromedio(array('min' => 12)); // WHERE promedio > 12
     * </code>
     *
     * @param     mixed $promedio The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function filterByPromedio($promedio = null, $comparison = null)
    {
        if (is_array($promedio)) {
            $useMinMax = false;
            if (isset($promedio['min'])) {
                $this->addUsingAlias(DatasetValoracionPeer::PROMEDIO, $promedio['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($promedio['max'])) {
                $this->addUsingAlias(DatasetValoracionPeer::PROMEDIO, $promedio['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DatasetValoracionPeer::PROMEDIO, $promedio, $comparison);
    }

    /**
     * Filter the query on the nvotos column
     *
     * Example usage:
     * <code>
     * $query->filterByNvotos(1234); // WHERE nvotos = 1234
     * $query->filterByNvotos(array(12, 34)); // WHERE nvotos IN (12, 34)
     * $query->filterByNvotos(array('min' => 12)); // WHERE nvotos > 12
     * </code>
     *
     * @param     mixed $nvotos The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function filterByNvotos($nvotos = null, $comparison = null)
    {
        if (is_array($nvotos)) {
            $useMinMax = false;
            if (isset($nvotos['min'])) {
                $this->addUsingAlias(DatasetValoracionPeer::NVOTOS, $nvotos['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($nvotos['max'])) {
                $this->addUsingAlias(DatasetValoracionPeer::NVOTOS, $nvotos['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(DatasetValoracionPeer::NVOTOS, $nvotos, $comparison);
    }

    /**
     * Filter the query by a related Dataset object
     *
     * @param   Dataset|PropelObjectCollection $dataset The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   DatasetValoracionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByDataset($dataset, $comparison = null)
    {
        if ($dataset instanceof Dataset) {
            return $this
                ->addUsingAlias(DatasetValoracionPeer::DATASET_ID, $dataset->getId(), $comparison);
        } elseif ($dataset instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(DatasetValoracionPeer::DATASET_ID, $dataset->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByDataset() only accepts arguments of type Dataset or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Dataset relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function joinDataset($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Dataset');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Dataset');
        }

        return $this;
    }

    /**
     * Use the Dataset relation Dataset object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   DatasetQuery A secondary query class using the current class as primary query
     */
    public function useDatasetQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinDataset($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Dataset', 'DatasetQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   DatasetValoracion $datasetValoracion Object to remove from the list of results
     *
     * @return DatasetValoracionQuery The current query, for fluid interface
     */
    public function prune($datasetValoracion = null)
    {
        if ($datasetValoracion) {
            $this->addUsingAlias(DatasetValoracionPeer::ID, $datasetValoracion->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
