<?php



/**
 * Skeleton subclass for performing query and update operations on the 'dataset_valoracion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat Jan  4 18:51:01 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class DatasetValoracionPeer extends BaseDatasetValoracionPeer
{
}
